# Generated by Django 5.0 on 2025-04-22 07:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 4, 22, 7, 7, 14, 261457, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
